[package]
name = "p3r"
version = "0.0.1"
authors = ["Frederic SERAPHINE <frederic＠designlab.ac>"]
edition = "2021"

[dependencies]
# Add your project's dependencies here
sha3 = "0.10.5"
bincode = "1.3.3" 
hex = "0.4.3"
serde = { version = "1.0.157",  features = ["derive"] }
serde_derive = "1.0.157"

[dev-dependencies]
# Add development dependencies here, if any

[[bin]]
name = "p3r"
path = "src/main.rs"

[lib]
name = "p3r_lib"
path = "src/lib.rs"

[features]
# Add your project's features here, if any

[build-dependencies]
# Add build dependencies here, if any
